services:
  static-web-client:
    build:
      context: ../applications/static-web-client
      dockerfile: dockerfile
    ports:
      - 8080:80


  server:
    build:
      context: ../applications/server
      dockerfile: dockerfile
    ports:
      - 3000:3000

  sensor-temperature:
    build:
      context: ../applications/sensor-temperature
      dockerfile: dockerfile
    network_mode: host